2023-01-19T10:11:14.6703921+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T10:11:14.6800500+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T10:11:14.6895501+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T10:11:14.6916492+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T10:11:14.6938718+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T10:15:37.9808458+05:00 0HMNPREBEG272:0000000D [ERR] No BOM found angainst given Item (ff8f3333)
2023-01-19T10:15:37.9808285+05:00 0HMNPREBEG272:0000000F [ERR] No BOM found angainst given Item (ff8f3333)
2023-01-19T10:26:36.0531355+05:00 0HMNPREBEG272:00000011 [ERR] No BOM found angainst given Item (ff8f3333)
2023-01-19T10:28:28.3625366+05:00 0HMNPREBEG272:00000013 [ERR] No BOM found angainst given Item (ff8f3333)
2023-01-19T10:36:51.4727092+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T10:36:51.4975049+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T10:36:51.5004445+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T10:36:51.5022812+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T10:36:51.5045122+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T10:50:47.9394480+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T10:50:47.9466380+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T10:50:47.9487522+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T10:50:47.9506183+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T10:50:47.9524089+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T10:52:02.0624794+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T10:52:02.0689673+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T10:52:02.0710400+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T10:52:02.0730446+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T10:52:02.0751315+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T10:55:41.8706270+05:00 0HMNPS54PSM09:00000005 [ERR] -5002:Invoice & receipt must be paid exactly  [OINV.GroupNum] (4d9f70d8)
2023-01-19T11:02:30.5714782+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T11:02:30.5781534+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T11:02:30.5801542+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T11:02:30.5833530+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T11:02:30.5854931+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T11:04:55.1233274+05:00 0HMNPSB016SVL:00000005 [ERR] -5002:Invoice & receipt must be paid exactly  [OINV.GroupNum] (4d9f70d8)
2023-01-19T11:09:46.2294780+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T11:09:46.2363639+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T11:09:46.2384872+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T11:09:46.2402864+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T11:09:46.2421066+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T11:12:39.0893848+05:00 0HMNPSF1UR12G:00000005 [ERR] -5002:Invoice & receipt must be paid exactly  [OINV.GroupNum] (4d9f70d8)
2023-01-19T11:16:38.0998551+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T11:16:38.1063308+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T11:16:38.1083987+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T11:16:38.1102489+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T11:16:38.1123839+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T11:17:24.5815433+05:00 0HMNPSISKDG2I:00000005 [ERR] -5002:Invoice & receipt must be paid exactly  [OINV.GroupNum] (4d9f70d8)
2023-01-19T11:17:24.5815625+05:00 0HMNPSISKDG2I:00000007 [ERR] -5002:Invoice & receipt must be paid exactly  [OINV.GroupNum] (4d9f70d8)
2023-01-19T11:18:09.8015920+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T11:18:09.8101249+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T11:18:09.8125014+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T11:18:09.8147191+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T11:18:09.8168966+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T11:20:54.0248461+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T11:20:54.0395631+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T11:20:54.0430053+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T11:20:54.0447393+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T11:20:54.0475872+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T11:21:26.4927433+05:00 0HMNPSL8SF0A2:00000005 [INF] Record added successfully (f95911fc)
2023-01-19T11:22:33.6020154+05:00  [INF] Application is shutting down... (90f52c38)
2023-01-19T11:44:16.1352027+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T11:44:16.1470807+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T11:44:16.1502010+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T11:44:16.1546053+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T11:44:16.1619793+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T11:44:44.3350286+05:00 0HMNPT2AN5V96:00000005 [ERR] AR Invoice Already Exist (dcc6474d)
2023-01-19T11:49:18.4662993+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T11:49:18.4732825+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T11:49:18.4753639+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T11:49:18.4774846+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T11:49:18.4801285+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T11:49:56.4793652+05:00 0HMNPT54UGUJ7:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.Runtime.InteropServices.COMException (0xFFFFFFFF): Invalid row
   at SAPbobsCOM.IDocumentsAdditionalExpenses.SetCurrentLine(Int32 LineNum)
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 191
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T11:51:37.5878478+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T11:51:37.5950681+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T11:51:37.5970816+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T11:51:37.5989674+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T11:51:37.6012239+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T11:52:31.6322780+05:00 0HMNPT6EAU99Q:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.Runtime.InteropServices.COMException (0xFFFFFFFF): Invalid row
   at SAPbobsCOM.IDocumentsAdditionalExpenses.SetCurrentLine(Int32 LineNum)
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 191
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T11:54:57.1602161+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T11:54:57.1668071+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T11:54:57.1690205+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T11:54:57.1708721+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T11:54:57.1726493+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T11:56:11.7230056+05:00 0HMNPT89Q5CCH:00000005 [INF] Record added successfully (f95911fc)
2023-01-19T11:57:58.3661446+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T11:57:58.3729960+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T11:57:58.3750487+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T11:57:58.3817727+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T11:57:58.3834359+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T11:59:37.9849614+05:00 0HMNPT9VS4UPF:00000005 [INF] Record added successfully (f95911fc)
2023-01-19T12:45:24.8324487+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T12:45:24.8393916+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T12:45:24.8415251+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T12:45:24.8434238+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T12:45:24.8453168+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T12:47:36.2079985+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T12:47:36.2151473+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T12:47:36.2176273+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T12:47:36.2204346+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T12:47:36.2252993+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T12:50:18.0408102+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T12:50:18.0479515+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T12:50:18.0501784+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T12:50:18.0522941+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T12:50:18.0542302+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T12:51:30.2960840+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T12:51:30.3030987+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T12:51:30.3049923+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T12:51:30.3067691+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T12:51:30.3086924+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T14:53:19.1425324+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T14:53:19.1681911+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T14:53:19.1795642+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T14:53:19.1985272+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T14:53:19.2198130+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T15:00:20.9011592+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T15:00:20.9076793+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T15:00:20.9096725+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T15:00:20.9130563+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T15:00:20.9153508+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T15:07:16.6253981+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T15:07:16.6435696+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T15:07:16.6459896+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T15:07:16.6481395+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T15:07:16.6499522+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T15:07:57.1203005+05:00 0HMNQ0JORV9QV:00000007 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 232
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T15:08:07.6957592+05:00 0HMNQ0JORV9QV:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 232
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T15:08:23.3071368+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T15:08:23.3251638+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T15:08:23.3435880+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T15:08:23.3728423+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T15:08:23.3777780+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T15:08:36.4653353+05:00 0HMNQ0KCLE42E:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 232
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T15:08:47.0918192+05:00 0HMNQ0KCLE42E:00000007 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 232
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T15:09:19.1644091+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T15:09:19.1715112+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T15:09:19.1741017+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T15:09:19.1761757+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T15:09:19.1824342+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T15:44:05.2773152+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T15:44:05.2854674+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T15:44:05.2878817+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T15:44:05.2898900+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T15:44:05.2918907+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T15:56:25.3639694+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T15:56:25.3723546+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T15:56:25.3760017+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T15:56:25.3863317+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T15:56:25.4006430+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T15:59:27.0004569+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T15:59:27.0091887+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T15:59:27.0113201+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T15:59:27.0129652+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T15:59:27.0149420+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T16:03:55.8827703+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T16:03:55.8894074+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T16:03:55.9008764+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T16:03:55.9034184+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T16:03:55.9053302+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T16:44:15.5153904+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T16:44:15.5224829+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T16:44:15.5246544+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T16:44:15.5274810+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T16:44:15.5298687+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T16:44:30.8280943+05:00 0HMNQ29V1B9J1:00000007 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at SAP_ARInvoice.Controllers.ARInvoiceController.<>c.<InvoiceMapper>b__4_4(DataModelSP x) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T16:44:32.1795003+05:00 0HMNQ29V1B9J1:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at SAP_ARInvoice.Controllers.ARInvoiceController.<>c.<InvoiceMapper>b__4_4(DataModelSP x) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T16:47:54.9945047+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T16:47:55.0015507+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T16:47:55.0045556+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T16:47:55.0065791+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T16:47:55.0086555+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T16:50:41.5041234+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T16:50:41.5115482+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T16:50:41.5144266+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T16:50:41.5188430+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T16:50:41.5219888+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T16:50:56.0279321+05:00 0HMNQ2DI30FO5:00000007 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at SAP_ARInvoice.Controllers.ARInvoiceController.<>c.<InvoiceMapper>b__4_4(DataModelSP x) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T16:51:00.1276498+05:00 0HMNQ2DI30FO5:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at SAP_ARInvoice.Controllers.ARInvoiceController.<>c.<InvoiceMapper>b__4_4(DataModelSP x) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T16:53:20.4122276+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T16:53:20.4188985+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T16:53:20.4208022+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T16:53:20.4227878+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T16:53:20.4247862+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T16:54:09.6324733+05:00 0HMNQ2F1D6923:00000007 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at SAP_ARInvoice.Controllers.ARInvoiceController.<>c.<InvoiceMapper>b__4_4(DataModelSP x) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T16:54:45.2557874+05:00 0HMNQ2F1D6923:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at SAP_ARInvoice.Controllers.ARInvoiceController.<>c.<InvoiceMapper>b__4_4(DataModelSP x) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T16:57:03.0567558+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T16:57:03.0636759+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T16:57:03.0658123+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T16:57:03.0676045+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T16:57:03.0697036+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T17:01:20.2236415+05:00 0HMNQ2H3NLF8V:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at SAP_ARInvoice.Controllers.ARInvoiceController.<>c.<InvoiceMapper>b__4_4(DataModelSP x) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T17:01:31.5438883+05:00 0HMNQ2H3NLF8V:00000007 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at SAP_ARInvoice.Controllers.ARInvoiceController.<>c.<InvoiceMapper>b__4_4(DataModelSP x) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T17:12:35.2155766+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T17:12:35.2237905+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T17:12:35.2261229+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T17:12:35.2280030+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T17:12:35.2299306+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T17:16:15.2159103+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T17:16:15.2228199+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T17:16:15.2248550+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T17:16:15.2274094+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T17:16:15.2294331+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T17:17:44.6001881+05:00 0HMNQ2RR4PUVH:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at SAP_ARInvoice.Controllers.ARInvoiceController.<>c.<InvoiceMapper>b__4_4(DataModelSP x) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T17:17:44.6001817+05:00 0HMNQ2RR4PUVH:00000007 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at SAP_ARInvoice.Controllers.ARInvoiceController.<>c.<InvoiceMapper>b__4_4(DataModelSP x) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SAP_ARInvoice.Controllers.ARInvoiceController.InvoiceMapper(List`1 data) in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 228
   at SAP_ARInvoice.Controllers.ARInvoiceController.GetAsync() in C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice\Controllers\ARInvoiceController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-01-19T17:21:04.2297716+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T17:21:04.2442204+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T17:21:04.2476622+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T17:21:04.2519942+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T17:21:04.2549607+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T17:36:22.2659708+05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2023-01-19T17:36:22.2736641+05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2023-01-19T17:36:22.2762367+05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2023-01-19T17:36:22.2788628+05:00  [INF] Hosting environment: "Development" (c3307c92)
2023-01-19T17:36:22.2829313+05:00  [INF] Content root path: "C:\Users\exd_Waheed\source\repos\SAP-ArInvoice-Test\SAP-ARInvoice" (b5d60022)
2023-01-19T17:37:33.9538448+05:00 0HMNQ372U6NGA:00000005 [ERR] Unable to Create New User (49a6e615)
